// Generated by CoffeeScript 1.6.3
define(function(require, exports, module) {
  var PathResolver;
  PathResolver = window.ShaderJs.Ast.PathResolver;
  return exports = describe("AST Utils", function() {
    describe("Environment", function() {
      it("has namespace 'window.ShaderJs.Ast'", function() {
        return expect(window.ShaderJs.Ast != null).toBe(true);
      });
      it("has class 'Path'", function() {
        return expect(window.ShaderJs.Ast.Path != null).toBe(true);
      });
      it("has class 'Dispatcher'", function() {
        return expect(window.ShaderJs.Ast.Dispatcher != null).toBe(true);
      });
      return it("has class 'Walker'", function() {
        return expect(window.ShaderJs.Ast.Walker != null).toBe(true);
      });
    });
    describe("PathResolver", function() {
      it("resolves path with no type constraints");
      it("resolves path with type constraints");
      it("resolves path with array accessor");
      return it("resolves path with array element accessor");
    });
    return describe("PathDispatcher", function() {
      it("dispatches simple map");
      it("dispatches nested map");
      return it("dispatches with return values");
    });
  });
});
