// Generated by CoffeeScript 1.6.3
define(function(require, exports, module) {
  return exports = describe("Compiler", function() {
    return describe("TypeResolver", function() {
      return it("resolves NewExpression", function() {
        var ast;
        ast = esprima.parse("var v4 = new Vec4()");
        return console.log(ast);
      });
    });
  });
});
