// Generated by CoffeeScript 1.6.3
define(function(require, exports, module) {
  var TypeResolver, strip;
  TypeResolver = window.ShaderJs.TypeResolver;
  strip = function(program) {
    return program.body[0];
  };
  return exports = describe("Compiler", function() {
    return describe("TypeResolver", function() {
      it("resolves NewExpression", function() {
        var ast, resolver, symbol;
        ast = strip(esprima.parse("var v4 = new Vec4()"));
        symbol = ast.declarations[0];
        symbol.scope = "test";
        resolver = new TypeResolver();
        resolver.resolve(symbol);
        expect(symbol.value_type).toEqual("Vec4");
        return console.log(resolver.type_table);
      });
      it("resolves build-in factory function");
      return it("evaluates binary expression");
    });
  });
});
