// Generated by CoffeeScript 1.6.3
define(function(require, exports, module) {
  return exports = {
    strip: function(program) {
      return program.body[0];
    },
    parseOne: function(js_line) {
      return this.strip(esprima.parse(js_line));
    }
  };
});
